### ISSUE TITLE
Trying to run in production mode fails with error

### ISSUE THREAD

**Issue by losh11** [jonathanbier/forkmonitor#182]
Development mode through webpack works fine, but attempting to deploy in production seems to fail.

```bash
$ bundle exec rake nodes:poll_repeat[BTC] --trace
** Invoke nodes:poll_repeat (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute nodes:poll_repeat
rake aborted!
NoMethodError: undefined method `check_versionbits!' for nil:NilClass
/home/litecoin/forkmonitor/app/models/node.rb:482:in `poll!'
/home/litecoin/forkmonitor/app/models/node.rb:502:in `block in poll_repeat!'
/home/litecoin/forkmonitor/app/models/node.rb:498:in `loop'
/home/litecoin/forkmonitor/app/models/node.rb:498:in `poll_repeat!'
/home/litecoin/forkmonitor/lib/tasks/nodes.rake:16:in `block (2 levels) in <main>'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/litecoin/.rvm/rubies/ruby-3.0.1/bin/rake:29:in `load'
/home/litecoin/.rvm/rubies/ruby-3.0.1/bin/rake:29:in `<top (required)>'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli.rb:494:in `exec'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:49:in `block in <top (required)>'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:37:in `<top (required)>'
/home/litecoin/.rvm/gems/ruby-3.0.1/bin/bundle:23:in `load'
/home/litecoin/.rvm/gems/ruby-3.0.1/bin/bundle:23:in `<main>'
Tasks: TOP => nodes:poll_repeat
```

```bash
$ bundle exec rake nodes:heavy_checks_repeat[BTC] --trace
** Invoke nodes:heavy_checks_repeat (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute nodes:heavy_checks_repeat
rake aborted!
NoMethodError: undefined method `-' for nil:NilClass
/home/litecoin/forkmonitor/app/models/stale_candidate.rb:363:in `block in index_json_cached'
/home/litecoin/.rvm/gems/ruby-3.0.1/gems/activesupport-6.1.3.2/lib/active_support/cache.rb:746:in `block in save_block_result_to_cache'
/home/litecoin/.rvm/gems/ruby-3.0.1/gems/activesupport-6.1.3.2/lib/active_support/cache.rb:720:in `block in instrument'
/home/litecoin/.rvm/gems/ruby-3.0.1/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:205:in `instrument'
/home/litecoin/.rvm/gems/ruby-3.0.1/gems/activesupport-6.1.3.2/lib/active_support/cache.rb:720:in `instrument'
/home/litecoin/.rvm/gems/ruby-3.0.1/gems/activesupport-6.1.3.2/lib/active_support/cache.rb:745:in `save_block_result_to_cache'
/home/litecoin/.rvm/gems/ruby-3.0.1/gems/activesupport-6.1.3.2/lib/active_support/cache.rb:337:in `fetch'
/home/litecoin/forkmonitor/app/models/stale_candidate.rb:362:in `index_json_cached'
/home/litecoin/forkmonitor/app/models/stale_candidate.rb:349:in `prime_cache'
/home/litecoin/forkmonitor/app/models/node.rb:639:in `block (2 levels) in heavy_checks_repeat!'
/home/litecoin/forkmonitor/app/models/node.rb:633:in `each'
/home/litecoin/forkmonitor/app/models/node.rb:633:in `block in heavy_checks_repeat!'
/home/litecoin/forkmonitor/app/models/node.rb:632:in `loop'
/home/litecoin/forkmonitor/app/models/node.rb:632:in `heavy_checks_repeat!'
/home/litecoin/forkmonitor/lib/tasks/nodes.rake:26:in `block (2 levels) in <main>'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:83:in `block in run'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib/rake/application.rb:80:in `run'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/litecoin/.rvm/rubies/ruby-3.0.1/bin/rake:29:in `load'
/home/litecoin/.rvm/rubies/ruby-3.0.1/bin/rake:29:in `<top (required)>'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `load'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:63:in `kernel_load'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli.rb:494:in `exec'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:49:in `block in <top (required)>'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.15/libexec/bundle:37:in `<top (required)>'
/home/litecoin/.rvm/gems/ruby-3.0.1/bin/bundle:23:in `load'
/home/litecoin/.rvm/gems/ruby-3.0.1/bin/bundle:23:in `<main>'
Tasks: TOP => nodes:heavy_checks_repeat
```

**Comment by Sjors** [comment]
When running for the first time, don't use the `_repeat` task. I also suggest waiting for `poll` to completely finish before running the heavy tasks. Though that's probably not the issue.

In development, where you able to run `bundle exec rake nodes:poll[BTC]`?

**Comment by Sjors** [comment]
The line of code that fails here is expecting at least one (enabled) Bitcoin Core node (marked as such in the admin panel)`.

If that's a problem in your setup, you could make a PR to skip this check instead of crashing.

**Comment by losh11** [comment]
I think I'm doing this wrong, and I would really appreciate some hand holding - would be excellent for improving documenting prod setup too. On a brand new Ubuntu 20.04 LTS system this is what I am doing so far:

```bash
# create user bitcoin
# create user fork_monitor
```

As user fork_monitor:
```bash
$ git clone https://github.com/BitMEXResearch/forkmonitor.git
# copy contents of /deploy to respective locations
# install python (via pyenv)
# install and run yarn (via nvm)
# setup postgres & create db fork_monitor & fork_monitor_test
# setup redis
```

As user bitcoin:
```bash
# build bitcoind with additional rpc
# sync bitcoind
# repeat for all forks
```

As user fork_monitor:
```bash
$ bundle exec rake db:schema:load
$ bundle install --without development
```

This is where I'm not totally sure what I'm doing... hopefully everything prior to this is correct, as it was pretty much the same for dev mode.

From what I understand nginx serves a prod built version of the React frontend, which is built to `forkmonitor/current`. Though I'm not sure what command actually builds to the current folder. And `bundle exec puma` runs the backend. However running this and trying to connect to `http://server_ip:port` results in a crash?

```bash 
$ bundle exec puma
[17786] Puma starting in cluster mode...
[17786] * Version 4.3.8 (ruby 3.0.1-p64), codename: Mysterious Traveller
[17786] * Min threads: 5, max threads: 5
[17786] * Environment: development
[17786] * Process workers: 2
[17786] * Preloading application
[17786] * Listening on tcp://0.0.0.0:3000
[17786] ! WARNING: Detected 5 Thread(s) started in app boot:
[17786] ! #<Thread:0x0000564d8e9f5a88 /home/litecoin/.rvm/gems/ruby-3.0.1/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:323 sleep> - /home/litecoin/.rvm/gems/ruby-3.0.1/gems/activerecord-6.1.3.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:329:in `sleep'
[17786] ! #<Thread:0x0000564d8f51d1b8@listen-run_thread /home/litecoin/.rvm/gems/ruby-3.0.1/gems/listen-3.5.1/lib/listen/thread.rb:17 sleep> - /home/litecoin/.rvm/gems/ruby-3.0.1/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:317:in `select'
[17786] ! #<Thread:0x0000564d8f50b5f8@listen-wait_thread /home/litecoin/.rvm/gems/ruby-3.0.1/gems/listen-3.5.1/lib/listen/thread.rb:17 sleep_forever> - /home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/forwardable.rb:238:in `pop'
[17786] ! #<Thread:0x0000564d8fe61bc0@listen-run_thread /home/litecoin/.rvm/gems/ruby-3.0.1/gems/listen-3.5.1/lib/listen/thread.rb:17 run> - /home/litecoin/.rvm/gems/ruby-3.0.1/gems/listen-3.5.1/lib/listen/record/entry.rb:27:in `mtime'
[17786] ! #<Thread:0x0000564d8fe60f40@listen-wait_thread /home/litecoin/.rvm/gems/ruby-3.0.1/gems/listen-3.5.1/lib/listen/thread.rb:17 sleep_forever> - /home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/forwardable.rb:238:in `pop'
[17786] Use Ctrl-C to stop
[17786] - Worker 1 (pid: 17822) booted, phase: 0
[17786] - Worker 0 (pid: 17818) booted, phase: 0
#
#
# <--------- this is when I connect to the server
# 
# 
#<Thread:0x00007f2d645de2e0 /home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/open3.rb:295 run> terminated with exception (report_on_exception is true):
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/open3.rb:295:in `read': stream closed in another thread (IOError)
        from /home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/open3.rb:295:in `block (2 levels) in capture3'
#<Thread:0x00007f2d645de1a0 /home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/open3.rb:296 run> terminated with exception (report_on_exception is true):
/home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/open3.rb:296:in `read': stream closed in another thread (IOError)
        from /home/litecoin/.rvm/rubies/ruby-3.0.1/lib/ruby/3.0.0/open3.rb:296:in `block (2 levels) in capture3'
```

**Comment by Sjors** [comment]
This is a good way to find missing stuff in [DEPLOYMENT.md](https://github.com/BitMEXResearch/forkmonitor/blob/master/DEPLOYMENT.md); I wrote that retroactively, so may have missed things.

I've you're trying to run a production server, then you have to make sure everything uses the `production` environment.

Start by prefixing any `bundle exec` command with `RAILS_ENV=production`. If I were you I would first try to get the database populated and the polling process working. This does not require the web server. Instead, use `RAILS_ENV=production bundle exec rails console` to inspect the database. You can manually add nodes there too.

The error you're seeing is probably because you need to precompile the javascript and css assets. Something like `bundle exec rake assets:precompile` should fix that.

Once you have production up and running, you should look into using Capistrano to deploy later updates. which takes care of database migrations and (re)compiling assets. Though `git pull` can work too.



However before building a production system, I think you should try a development environment first. This doesn't require `nginx` and should make debugging easier. It may also be easier to try with testnet, running all the rake tasks with `[TBTC]`. The instructions for that - which again may be outdated - are in [DEVELOPMENT.md](https://github.com/BitMEXResearch/forkmonitor/blob/master/DEVELOPMENT.md).

**Comment by Sjors** [comment]
That's a very cryptic error message I haven't seen before. On your node, you should be able to log RPC calls (`-debug=rpc`): do you see any attempt?

(also rpcport shouldn't be filtered, that's a bug, but doesn't matter)

> when I try to add a node through the admin dashboard

When you add a node through the dashboard I believe it immediately tries to connect to it, so that might be why you're seeing the same failure.

No need to add it twice though, just do `Node.first` next time you fire up the console.

(if it's already duplicated, just delete one, e.g. `Node.second.destroy`

**Comment by losh11** [comment]
Okay I've taken a deeper look, and it seems to be an uncommon issue that some people running ruby on macOS are experiencing. However the commonly recommended fix doesn't seem to work. Although I haven't attempted repeating this on another Mac, perhaps this should be added as a notice in `development.md`. Tried on my Ubuntu 20.04 machine, and there's no such issue. Currently polling and syncing.

I had two different nodes connected.

Would you mind if I kept this issue open so I can track all issues experienced whilst trying to deploy forkmonitor? Or would you like me to open a new issue for each issue? When I'm done, I'll create a PR updating the dev/prod instructions :)

**Comment by Sjors** [comment]
Mmm, well Rvm should probably work just as well, though you could try rbenv; it's more light-weight.

**Comment by Sjors** [comment]
Closing since much has changed since last year, including a newer ruby version. Feel free to comment here or open a new issue if you're still trying. I would also suggest running the site on Ubuntu, as it tends to give fewer headaches than macOS.
